### YamlMime:Lifecycle
metadata:
  title: Microsoft Intelligent Application Gateway 2007 -sovellus
  description: Microsoft Intelligent Application Gateway 2007 noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 07/28/2020
  ms.openlocfilehash: 6e5cc4784788d27433b7525f6a900cbc1e9f0713
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "814955"
name: Microsoft Intelligent Application Gateway 2007 -sovellus
summary: >
  Microsoft Intelligent Application Gateway 2007 noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä.



  > [!IMPORTANT]

  > Tämän tuotteen tuki on päättynyt. Katso alla oleva siirtymäohjeet.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 06/01/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Service Pack 2
  startDate: 11/27/2008
  endDate: 07/11/2017
- version: Service Pack 1
  startDate: 09/03/2007
  endDate: 01/12/2010
- version: Original Release
  startDate: 06/01/2007
  endDate: 10/14/2008
content: "\n## <a name=\"links\"></a>Linkkejä \n* [Microsoft Intelligent Application Gateway 2007 -etenemissuunnitelma](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [Service Pack -käytäntö](/lifecycle/policies/fixed#service-packs)"
