### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 07/28/2020
  ms.openlocfilehash: 1066e1999c057459643c64aba46bb88e34bb4842
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4137418"
name: Microsoft System Center Configuration Manager 2007 R3
summary: "Microsoft System Center Configuration Manager 2007 R3 noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä. \n\n\n> [!IMPORTANT]\n> Tämän tuotteen tuki on päättynyt. Katso siirtymäohjeet alta.\n"
products:
- msc
policyType: fixed
supportDates:
  start: 2010-12-19T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2010-12-19T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Linkit \n* [Siirron ohjeistus](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Siirtymistä koskevat lisäohjeet](/mem/configmgr/core/migration/planning-for-migration)"
