### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security noudattaa kiinteää elin kaari käytäntöä.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908710"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security noudattaa [kiinteää](/lifecycle/policies/fixed) elin kaari käytäntöä.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Linkit \n* [Järjestelmä keskuksen pääte pisteen suojaus](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security on lopetettu. Tuki päättyy 14 heinäkuu, 2015. Antimalware-ja antispyware-määritysten päivitykset eivät ole enää käytettävissä tuote version tuen päättymisen jälkeen. Arvioi System Center Endpoint Protectionia korvaavana."
