### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.0
  description: Microsoft Application Virtualization 5.0 noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Terminal Services,for Windows Desktops
  ms.openlocfilehash: 6f4b9be47350fce8f81af5516776520ac293cadc
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4139749"
name: Microsoft Application Virtualization 5.0
summary: "Microsoft Application Virtualization 5.0 noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä. \n\nTämä koskee seuraavia versioita: for Remote Desktop Services, for Terminal Services, for Windows Desktops\n\n"
products:
- windows
policyType: fixed
supportDates:
  start: 2012-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2023-01-10T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2014-12-08T00:00:00.000-08:00
  endDate: 2023-01-10T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2016-01-12T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2013-04-10T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Original Release
  startDate: 2012-11-01T00:00:00.000-08:00
  endDate: 2014-07-08T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Linkit \n* [Tuotteen tiedot](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n* [Service Pack -käytäntö](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Versiot \n* for Remote Desktop Services\n* for Terminal Services\n* for Windows Desktops"
