### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security noudattaa kiinteää elin kaari käytäntöä.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924252"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security noudattaa [kiinteää](/lifecycle/policies/fixed) elin kaari käytäntöä.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Linkit \n* [Järjestelmä keskuksen pääte pisteen suojaus](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Securityn käyttö on lopetettu 14 heinä kuuta 2015. Antimalware-ja antispyware-määritysten päivitykset eivät ole enää käytettävissä tuote version tuen päättymisen jälkeen. Arvioi System Center Endpoint Protectionia korvaavana."
