### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Microsoft System Center Configuration Manager 2007 R2 noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 07/28/2020
  ms.openlocfilehash: d74ead7a94de9a66a4f34abab6d8ff9b4496c86479bf1242d36b903855a6e66f
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511274"
name: Microsoft System Center Configuration Manager 2007 R2
summary: "Microsoft System Center Configuration Manager 2007 R2 noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä. \n\n\n> [!IMPORTANT]\n> Tämän tuotteen tuki on päättynyt. Katso siirtymäohjeet alta.\n"
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Linkit \n* [Siirron ohjeistus](/mem/configmgr/core/migration/planning-for-migration)\n* [Siirtymistä koskevat lisäohjeet](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
