### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113405"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä.


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Linkit \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security lopetettiin 14.7.2015. Haittaohjelmien ja vakoiluohjelmien torjuntamääritysten päivitykset eivät ole enää saatavilla tuoteversion tuen päätyttyä. Arvioi System Center Endpoint Protection korvaavana tuotteena."
