### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 8a32729ae5fbf7f57a14b6a6ec048c7a1f412a52
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935446"
name: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
summary: "Microsoft Application Virtualization Hosting 4.6 for Windows Desktops noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä. \n\nTämä koskee seuraavia versioita: for Windows Desktops\n\n"
products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Linkit \n* [Tuote- ja siirtotiedot](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Service Pack -käytäntö](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Koska App-V 4.6 -asiakasohjelma käyttää App-V 4.5-palvelinta, App-V 4.5-palvelinta tuetaan edelleen App-V 4.6:n elinkaaripäivien mukaan, kun sitä käytetään tuetun App-V 4.6 -asiakasohjelman kanssa.\n\n## <a name=\"editions\"></a>Versiot \n* for Windows Desktops"
