### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 Windows-työpöytiä
  description: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "814932"
name: Microsoft Application Virtualization Hosting 4.6 Windows-työpöytiä
summary: >+
  Microsoft Application Virtualization Hosting 4.6 for Windows Desktops noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä.


  Tämä koskee seuraavia versioita: Windowsin pöytätietokoneille

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Linkkejä \n* [Tuote- ja siirtotiedot](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Service Pack -käytäntö](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Koska App-V 4.6 -asiakas käyttää App-V 4.5 Serveriä, App-V 4.5 Serveriä tuetaan edelleen App-V 4.6:n elinkaaripäivien mukaan, kun sitä käytetään tuetun App-V 4.6 -asiakkaan kanssa.\n\n## <a name=\"editions\"></a>Versiot \n* Windows-työpöytiä varten"
