### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6 noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 09/01/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops,Sequencer'
name: Microsoft Application Virtualization 4.6
summary: |+
  Microsoft Application Virtualization 4.6 noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä.

  Tämä koskee seuraavia versioita: for Remote Desktop Services, for Windows Desktops, Sequencer

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Linkit 
  * [Tuote- ja siirtotiedot](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Siirron ohjeistus](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)
  * [Service Pack -käytäntö](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Koska App-V 4.6 -asiakasohjelma käyttää App-V 4.5-palvelinta, App-V 4.5-palvelinta tuetaan edelleen App-V 4.6:n elinkaaripäivien mukaan, kun sitä käytetään tuetun App-V 4.6 -asiakasohjelman kanssa.

  ## <a name="editions"></a>Versiot 
  * for Remote Desktop Services
  * for Windows Desktops
  * Sequencer