### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 09/10/2020
  keywords: '4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1'
name: SoftGrid Application Virtualization
summary: |
  SoftGrid Application Virtualization noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä.

  Tämä koskee seuraavia versioita: 4.1 työpöytäversioille, 4.2 työpöytäversioille, Terminal Services 4.1:lle

  > [!IMPORTANT]
  > Tuki on päättynyt. Katso siirtymäohjeet alta.
products:
  - windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
  - version: Original Release
    startDate: 05/25/2007
    endDate: 07/11/2017
content: |

  ## <a name="links"></a>Linkit 
  * [Siirron ohjeistus](https://technet.microsoft.com/en-us/windows/bb899442)


  ## <a name="editions"></a>Versiot 
  * 4.1 työpöytäversio
  * 4.2 työpöytäversio
  * Terminal Services 4.1:lle