### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization noudattaa kiinteää elinkaarikäytäntöä.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: fi-FI
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "814234"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization noudattaa [kiinteää](/lifecycle/policies/fixed) elinkaarikäytäntöä.


  Tämä koskee seuraavia versioita: 4.1 työpöytäversioille, 4.2 työpöytäversioille, Terminal Services 4.1:lle


  > [!IMPORTANT]

  > Tuki on päättynyt. Katso siirtymäohjeet alta.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Linkit \n* [Siirron ohjeistus](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Versiot \n* 4.1 työpöytäversio\n* 4.2 työpöytäversio\n* Terminal Services 4.1:lle"
